
//
// Bitmap font C header file generated by bmfont2c.py 
// 

#ifndef __BITMAP_FONT_DEFINITION__
#define __BITMAP_FONT_DEFINITION__


typedef struct
{
    unsigned char GlyphCount;
    unsigned char FirstAsciiCode;
    unsigned char GlyphBytesWidth;
    unsigned char GlyphHeight;
    unsigned char FixedWidth;
    unsigned char const *GlyphWidth;
    unsigned char const *GlyphBitmaps;
} fontStyle_t;


extern const fontStyle_t FontStyle_Consolas12;


#endif /* __BITMAP_FONT_DEFINITION__ */
